<a href="https://colab.research.google.com/github/Saifullah785/python-for-data-analysis-notes/blob/main/Chapter_04_NumPy_Basics%3A_Arrays_and_Vectorized_Computation/Chapter_04_NumPy_Basics__Arrays_and_Vectorized_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy_Basics:_Arrays_and_Vectorized_Computation**

In [90]:
# Import necessary libraries
import numpy as np
np.random.seed(12345) # Set a random seed for reproducibility
import matplotlib.pyplot as plt # Import matplotlib for plotting (though not used in this notebook yet)
plt.rc('figure', figsize=(10, 6)) # Set default figure size for matplotlib plots
np.set_printoptions(precision=4, suppress=True) # Set NumPy print options for better readability

In [91]:
# Create a large NumPy array and a large Python list
import numpy as np
my_arr = np.arange(1000000) # Create a NumPy array with numbers from 0 to 999999
my_list = list(range(1000000)) # Create a Python list with numbers from 0 to 999999

In [92]:
# Display the NumPy array
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [93]:
# Compare the performance of NumPy array multiplication and Python list multiplication
%timeit my_arr2 = my_arr * 2 # Measure time for multiplying NumPy array by 2
%timeit my_list2 = [x * 2 for x in my_list] # Measure time for multiplying Python list by 2 using a list comprehension

1.08 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
50.5 ms ± 2.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [94]:
# Create a 2D NumPy array
import numpy as np
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]]) # Create a 2x3 NumPy array
data # Display the array

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [95]:
# Perform element-wise operations on the NumPy array
data * 10 # Multiply each element by 10

data + data # Add the array to itself (element-wise addition)

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [96]:
# Check the shape and data type of the NumPy array
data.shape # Get the dimensions of the array (rows, columns)
data.dtype # Get the data type of the array elements

dtype('float64')

In [97]:
# Create a 1D NumPy array from a Python list
data1 = [6, 7.5, 8, 0, 1] # Python list
arr1 = np.array(data1) # Convert list to NumPy array
arr1 # Display the array

array([6. , 7.5, 8. , 0. , 1. ])

In [98]:
# Create a 2D NumPy array from a list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # Python list of lists
arr2 = np.array(data2) # Convert list of lists to NumPy array
arr2 # Display the array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
# Check the number of dimensions of the 2D array
arr2.ndim # Get the number of dimensions

2

In [100]:
# Check the shape of the 2D array
arr2.shape # Get the dimensions (rows, columns)

(2, 4)

In [101]:
# Check the data types of the 1D and 2D arrays
arr1.dtype # Data type of arr1
arr2.dtype # Data type of arr2

dtype('int64')

In [102]:
# Create a 1D array of zeros
np.zeros(10) # Create an array of 10 zeros with default float dtype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
# Create a 2D array of zeros
np.zeros((3, 6)) # Create a 3x6 array of zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [104]:
# Create an empty 3D array
np.empty((2, 3, 2)) # Create a 2x3x2 array with uninitialized (arbitrary) data

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [105]:
# Create a 1D array with a range of numbers
np.arange(15) # Create an array with numbers from 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
# Create NumPy arrays with specified data types
arr1 = np.array([1, 2, 3], dtype = np.float64) # Create array with float64 dtype
arr2 = np.array([1, 2, 3], dtype = np.int32) # Create array with int32 dtype

arr1.dtype # Check the data type of arr1

dtype('float64')

In [107]:
# Check the data type of arr2
arr2.dtype # Data type of arr2

dtype('int32')

In [108]:
# Create an integer array and check its data type
arr = np.array([1, 2, 3, 4, 5]) # Create an integer array

arr.dtype # Check the data type

dtype('int64')

In [109]:
# Cast the integer array to a float array
float_arr = arr.astype(np.float64) # Convert array elements to float64
float_arr # Display the new array

array([1., 2., 3., 4., 5.])

In [110]:
# Check the data type of the new float array
float_arr.dtype # Check the data type

dtype('float64')

In [111]:
# Create a float array
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1]) # Create a float array
arr # Display the array

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [112]:
# Cast the float array to an integer array (truncates decimal part)
arr.astype(np.int32) # Convert array elements to int32

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [113]:
# Convert an array of numeric strings to a float array
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.bytes_) # Create an array of bytes representing numbers
numeric_strings.astype(float) # Convert the elements to float

array([ 1.25, -9.6 , 42.  ])

In [114]:
# Cast an integer array to the data type of another array
int_array = np.arange(10) # Create an integer array
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64) # Create a float array
int_array.astype(calibers.dtype) # Convert int_array to the dtype of calibers (float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [115]:
# Create an array of zeros with an unsigned 32-bit integer data type
zero_uint32 = np.zeros(8, dtype = 'u4') # Create an array of 8 zeros with unsigned 32-bit integer dtype
zero_uint32 # Display the array

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [116]:
# Create a 2D NumPy array
arr = np.array ([[1., 2., 3.], [4., 5., 6.]]) # Create a 2x3 array
arr # Display the array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [117]:
# Perform element-wise multiplication
arr * arr # Multiply each element by itself

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [118]:
# Perform element-wise subtraction
arr - arr # Subtract each element from itself

array([[0., 0., 0.],
       [0., 0., 0.]])

In [119]:
# Perform element-wise division
1 / arr # Divide 1 by each element

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [120]:
# Perform element-wise exponentiation
arr **2 # Square each element

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [121]:
# Create another 2D NumPy array
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) # Create a new 2x3 array
arr2 # Display the array

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [122]:
# Perform element-wise comparison
arr2 > arr # Compare elements of arr2 with corresponding elements of arr

array([[False,  True, False],
       [ True, False,  True]])

In [123]:
# Create a 1D array
arr = np.arange(10) # Create an array with numbers from 0 to 9

arr # Display the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
# Access an element at a specific index
arr[5] # Get the element at index 5 (0-based indexing)

np.int64(5)

In [125]:
# Access a slice of the array
arr[5:8] # Get elements from index 5 up to (but not including) index 8

array([5, 6, 7])

In [126]:
# Assign a value to a slice of the array
arr[5:8] = 12 # Set elements from index 5 to 7 to the value 12

In [127]:
# Display the modified array
arr # Display the array

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [128]:
# Create a slice of the array
arr_slice = arr[5:8] # Create a view of the array from index 5 to 7
arr_slice # Display the slice

array([12, 12, 12])

In [129]:
# Modify an element in the slice (this also modifies the original array)
arr_slice[1] = 12345 # Change the element at index 1 of the slice (which is index 6 of the original array)
arr # Display the original array to see the change

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [130]:
# Modify the entire slice (this also modifies the original array)
arr_slice[:] = 64 # Set all elements in the slice to 64
arr # Display the original array to see the change

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [131]:
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Create a 3x3 array
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
# Access an element in a 2D array using double brackets
arr2d[0][2] # Get the element at row 0, column 2

np.int64(3)

In [133]:
# Access an element in a 2D array using single brackets with comma separation (preferred)
arr2d[0, 2] # Get the element at row 0, column 2

np.int64(3)

In [134]:
# Create a 3D array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # Create a 2x2x3 array
arr3d # Display the array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [135]:
# Access a 2D slice (a "layer") from the 3D array
arr3d[0] # Get the first 2D array (at index 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
# Create a copy of a slice from the 3D array
old_values = arr3d[0].copy() # Create a copy of the first 2D array
old_values # Display the copy

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
# Assign a scalar value to a 2D slice of the 3D array
arr3d[0] = 42 # Set all elements in the first 2D array to 42
arr3d # Display the modified 3D array

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [138]:
# Restore the original values to the 2D slice using the copy
arr3d[0] = old_values # Assign the copied values back to the first 2D array
arr3d # Display the restored 3D array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [139]:
# Access a 1D slice (a "row") from a 2D slice of the 3D array
arr3d[1, 0] # Get the first row (at index 0) of the second 2D array (at index 1)

array([7, 8, 9])

In [140]:
# Create a variable referencing a 2D slice from the 3D array
x = arr3d[1] # x is a view of the second 2D array
x # Display x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [141]:
# Access a row from the referenced 2D slice
x[0] # Get the first row of the 2D array x

array([7, 8, 9])

In [142]:
# Display the 1D array 'arr'
arr # Display the array

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [143]:
# Access a slice from the 1D array
arr[1:6] # Get elements from index 1 up to (but not including) index 6

array([ 1,  2,  3,  4, 64])

In [144]:
# Display the 2D array 'arr2d'
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
# Access the first two rows of the 2D array
arr2d[:2] # Get rows from the beginning up to (but not including) index 2

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
# Access a slice of rows and columns from the 2D array
arr2d[:2, 1:] # Get rows from the beginning up to index 2, and columns from index 1 to the end

array([[2, 3],
       [5, 6]])

In [147]:
# Access a specific row and a slice of columns, resulting in a lower-dimensional array
lower_dim_slice = arr2d[1, :2] # Get the second row (index 1) and columns from the beginning up to index 2
lower_dim_slice # Display the resulting 1D array

array([4, 5])

In [148]:
# Check the shape of the lower-dimensional slice
lower_dim_slice.shape # Get the dimensions of the slice

(2,)

In [149]:
# Display the 2D array 'arr2d' again
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
# Access a slice of rows and a specific column
arr2d[:2, 2] # Get rows from the beginning up to index 2, and the column at index 2

array([3, 6])

In [151]:
# Access all rows and the first column
arr2d[:, :1] # Get all rows and the column from the beginning up to (but not including) index 1 (results in a 2D array with 1 column)

array([[1],
       [4],
       [7]])

In [152]:
# Assign a scalar value to a slice of rows and columns
arr2d[:2, 1:] = 0 # Set elements in the first two rows and from the second column onwards to 0

In [153]:
# Display the modified 2D array
arr2d # Display the array after modification

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])