<a href="https://colab.research.google.com/github/Saifullah785/python-for-data-analysis-notes/blob/main/Chapter_04_NumPy_Basics%3A_Arrays_and_Vectorized_Computation/Chapter_04_NumPy_Basics__Arrays_and_Vectorized_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy_Basics:_Arrays_and_Vectorized_Computation**

In [2]:
# Import necessary libraries
import numpy as np
np.random.seed(12345) # Set a random seed for reproducibility
import matplotlib.pyplot as plt # Import matplotlib for plotting (though not used in this notebook yet)
plt.rc('figure', figsize=(10, 6)) # Set default figure size for matplotlib plots
np.set_printoptions(precision=4, suppress=True) # Set NumPy print options for better readability

In [3]:
# Create a large NumPy array and a large Python list
import numpy as np
my_arr = np.arange(1000000) # Create a NumPy array with numbers from 0 to 999999
my_list = list(range(1000000)) # Create a Python list with numbers from 0 to 999999

In [120]:
# Display the NumPy array
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
# Compare the performance of NumPy array multiplication and Python list multiplication
%timeit my_arr2 = my_arr * 2 # Measure time for multiplying NumPy array by 2
%timeit my_list2 = [x * 2 for x in my_list] # Measure time for multiplying Python list by 2 using a list comprehension

2.13 ms ± 206 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
61.2 ms ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [121]:
# Create a 2D NumPy array
import numpy as np
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]]) # Create a 2x3 NumPy array
data # Display the array

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [122]:
# Perform element-wise operations on the NumPy array
data * 10 # Multiply each element by 10

data + data # Add the array to itself (element-wise addition)

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [123]:
# Check the shape and data type of the NumPy array
data.shape # Get the dimensions of the array (rows, columns)
data.dtype # Get the data type of the array elements

dtype('float64')

In [124]:
# Create a 1D NumPy array from a Python list
data1 = [6, 7.5, 8, 0, 1] # Python list
arr1 = np.array(data1) # Convert list to NumPy array
arr1 # Display the array

array([6. , 7.5, 8. , 0. , 1. ])

In [125]:
# Create a 2D NumPy array from a list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # Python list of lists
arr2 = np.array(data2) # Convert list of lists to NumPy array
arr2 # Display the array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
# Check the number of dimensions of the 2D array
arr2.ndim # Get the number of dimensions

2

In [127]:
# Check the shape of the 2D array
arr2.shape # Get the dimensions (rows, columns)

(2, 4)

In [128]:
# Check the data types of the 1D and 2D arrays
arr1.dtype # Data type of arr1
arr2.dtype # Data type of arr2

dtype('int64')

In [129]:
# Create a 1D array of zeros
np.zeros(10) # Create an array of 10 zeros with default float dtype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
# Create a 2D array of zeros
np.zeros((3, 6)) # Create a 3x6 array of zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [131]:
# Create an empty 3D array
np.empty((2, 3, 2)) # Create a 2x3x2 array with uninitialized (arbitrary) data

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [132]:
# Create a 1D array with a range of numbers
np.arange(15) # Create an array with numbers from 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [133]:
# Create NumPy arrays with specified data types
arr1 = np.array([1, 2, 3], dtype = np.float64) # Create array with float64 dtype
arr2 = np.array([1, 2, 3], dtype = np.int32) # Create array with int32 dtype

arr1.dtype # Check the data type of arr1

dtype('float64')

In [134]:
# Check the data type of arr2
arr2.dtype # Data type of arr2

dtype('int32')

In [135]:
# Create an integer array and check its data type
arr = np.array([1, 2, 3, 4, 5]) # Create an integer array

arr.dtype # Check the data type

dtype('int64')

In [136]:
# Cast the integer array to a float array
float_arr = arr.astype(np.float64) # Convert array elements to float64
float_arr # Display the new array

array([1., 2., 3., 4., 5.])

In [137]:
# Check the data type of the new float array
float_arr.dtype # Check the data type

dtype('float64')

In [138]:
# Create a float array
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1]) # Create a float array
arr # Display the array

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [139]:
# Cast the float array to an integer array (truncates decimal part)
arr.astype(np.int32) # Convert array elements to int32

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [140]:
# Convert an array of numeric strings to a float array
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.bytes_) # Create an array of bytes representing numbers
numeric_strings.astype(float) # Convert the elements to float

array([ 1.25, -9.6 , 42.  ])

In [141]:
# Cast an integer array to the data type of another array
int_array = np.arange(10) # Create an integer array
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64) # Create a float array
int_array.astype(calibers.dtype) # Convert int_array to the dtype of calibers (float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [142]:
# Create an array of zeros with an unsigned 32-bit integer data type
zero_uint32 = np.zeros(8, dtype = 'u4') # Create an array of 8 zeros with unsigned 32-bit integer dtype
zero_uint32 # Display the array

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [143]:
# Create a 2D NumPy array
arr = np.array ([[1., 2., 3.], [4., 5., 6.]]) # Create a 2x3 array
arr # Display the array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [144]:
# Perform element-wise multiplication
arr * arr # Multiply each element by itself

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [145]:
# Perform element-wise subtraction
arr - arr # Subtract each element from itself

array([[0., 0., 0.],
       [0., 0., 0.]])

In [146]:
# Perform element-wise division
1 / arr # Divide 1 by each element

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [147]:
# Perform element-wise exponentiation
arr **2 # Square each element

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [148]:
# Create another 2D NumPy array
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) # Create a new 2x3 array
arr2 # Display the array

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [149]:
# Perform element-wise comparison
arr2 > arr # Compare elements of arr2 with corresponding elements of arr

array([[False,  True, False],
       [ True, False,  True]])

In [150]:
# Create a 1D array
arr = np.arange(10) # Create an array with numbers from 0 to 9

arr # Display the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
# Access an element at a specific index
arr[5] # Get the element at index 5 (0-based indexing)

np.int64(5)

In [152]:
# Access a slice of the array
arr[5:8] # Get elements from index 5 up to (but not including) index 8

array([5, 6, 7])

In [153]:
# Assign a value to a slice of the array
arr[5:8] = 12 # Set elements from index 5 to 7 to the value 12

In [154]:
# Display the modified array
arr # Display the array

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [155]:
# Create a slice of the array
arr_slice = arr[5:8] # Create a view of the array from index 5 to 7
arr_slice # Display the slice

array([12, 12, 12])

In [156]:
# Modify an element in the slice (this also modifies the original array)
arr_slice[1] = 12345 # Change the element at index 1 of the slice (which is index 6 of the original array)
arr # Display the original array to see the change

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [157]:
# Modify the entire slice (this also modifies the original array)
arr_slice[:] = 64 # Set all elements in the slice to 64
arr # Display the original array to see the change

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [158]:
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Create a 3x3 array
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
# Access an element in a 2D array using double brackets
arr2d[0][2] # Get the element at row 0, column 2

np.int64(3)

In [160]:
# Access an element in a 2D array using single brackets with comma separation (preferred)
arr2d[0, 2] # Get the element at row 0, column 2

np.int64(3)

In [161]:
# Create a 3D array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # Create a 2x2x3 array
arr3d # Display the array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [162]:
# Access a 2D slice (a "layer") from the 3D array
arr3d[0] # Get the first 2D array (at index 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
# Create a copy of a slice from the 3D array
old_values = arr3d[0].copy() # Create a copy of the first 2D array
old_values # Display the copy

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
# Assign a scalar value to a 2D slice of the 3D array
arr3d[0] = 42 # Set all elements in the first 2D array to 42
arr3d # Display the modified 3D array

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [165]:
# Restore the original values to the 2D slice using the copy
arr3d[0] = old_values # Assign the copied values back to the first 2D array
arr3d # Display the restored 3D array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [166]:
# Access a 1D slice (a "row") from a 2D slice of the 3D array
arr3d[1, 0] # Get the first row (at index 0) of the second 2D array (at index 1)

array([7, 8, 9])

In [167]:
# Create a variable referencing a 2D slice from the 3D array
x = arr3d[1] # x is a view of the second 2D array
x # Display x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [168]:
# Access a row from the referenced 2D slice
x[0] # Get the first row of the 2D array x

array([7, 8, 9])

In [169]:
# Display the 1D array 'arr'
arr # Display the array

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [170]:
# Access a slice from the 1D array
arr[1:6] # Get elements from index 1 up to (but not including) index 6

array([ 1,  2,  3,  4, 64])

In [171]:
# Display the 2D array 'arr2d'
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
# Access the first two rows of the 2D array
arr2d[:2] # Get rows from the beginning up to (but not including) index 2

array([[1, 2, 3],
       [4, 5, 6]])

In [173]:
# Access a slice of rows and columns from the 2D array
arr2d[:2, 1:] # Get rows from the beginning up to index 2, and columns from index 1 to the end

array([[2, 3],
       [5, 6]])

In [174]:
# Access a specific row and a slice of columns, resulting in a lower-dimensional array
lower_dim_slice = arr2d[1, :2] # Get the second row (index 1) and columns from the beginning up to index 2
lower_dim_slice # Display the resulting 1D array

array([4, 5])

In [175]:
# Check the shape of the lower-dimensional slice
lower_dim_slice.shape # Get the dimensions of the slice

(2,)

In [176]:
# Display the 2D array 'arr2d' again
arr2d # Display the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
# Access a slice of rows and a specific column
arr2d[:2, 2] # Get rows from the beginning up to index 2, and the column at index 2

array([3, 6])

In [178]:
# Access all rows and the first column
arr2d[:, :1] # Get all rows and the column from the beginning up to (but not including) index 1 (results in a 2D array with 1 column)

array([[1],
       [4],
       [7]])

In [179]:
# Assign a scalar value to a slice of rows and columns
arr2d[:2, 1:] = 0 # Set elements in the first two rows and from the second column onwards to 0

In [180]:
# Display the modified 2D array
arr2d # Display the array after modification

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [181]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # Create an array of names
names # Display the array

data = np.array([[4,7],[0,2],[-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]]) # Create a 2D array of data
names # Display the names array again
data # Display the data array again

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [182]:
# Perform a boolean comparison on the names array
names == "bob" # Check which elements in names are equal to "bob" (case-sensitive)

array([False, False, False, False, False, False, False])

In [183]:
# Use boolean indexing to select rows from data where names is "bob"
data[names == "bob"] # Select rows from data where the corresponding element in names is True

array([], shape=(0, 2), dtype=int64)

In [184]:
# Use boolean indexing and column slicing to select data
data[names == "bob", 1:] # Select rows where names is "bob" and columns from index 1 to the end

array([], shape=(0, 1), dtype=int64)

In [185]:
# Use boolean indexing and specific column selection to select data
data[names == 'bob', 1] # Select rows where names is "bob" and the element at column index 1

array([], dtype=int64)

In [186]:
# Perform boolean comparisons and negation
names != 'bob' # Check which elements in names are not equal to "bob"

~(names == 'bob') # Negate the boolean array from the previous comparison (equivalent to names != 'bob')

data[~(names == 'bob')] # Use the negated boolean array to select rows from data where names is not "bob"

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [187]:
# Create a boolean condition and use it for indexing
cond = names == 'Bob' # Create a boolean array where True indicates "Bob"

data[~cond] # Use the negated boolean array to select rows from data where names is not "Bob"

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [188]:
# Combine boolean conditions using the OR operator
mask = (names == 'Bob') | (names == 'Will') # Create a boolean mask where True indicates "Bob" or "Will"

mask # Display the boolean mask

data[mask] # Use the mask to select rows from data where names is "Bob" or "Will"

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [189]:
# Use a boolean array to set values in a data array
data[data < 0] = 0 # Set all elements in data that are less than 0 to 0
data # Display the modified data array

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [190]:
# Use a boolean array to set values in rows of a data array
data[names != 'Joe'] =7 # Set all rows in data where the corresponding name is not "Joe" to the value 7
data # Display the modified data array

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [191]:
# Create an 8x4 array of zeros and assign row indices to each row
arr = np.zeros((8, 4)) # Create an 8x4 array of zeros
for i in range(8): # Iterate through each row index
  arr[i] = i # Assign the row index as the value for all elements in that row
arr # Display the array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [192]:
# Select rows from an array using a list of indices
arr[[4, 3, 0, 6]] # Select rows at index 4, 3, 0, and 6 in that order

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [193]:
# Select rows from an array using a list of negative indices
arr[[-3, -5, -7]] # Select rows at index -3, -5, and -7 (counting from the end)

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [194]:
# Create and reshape an array with a range of numbers
arr = np.arange(32).reshape((8, 4)) # Create an array with numbers from 0 to 31 and reshape it to 8 rows and 4 columns
arr # Display the array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [195]:
# Select specific elements from different rows and columns using paired lists of indices
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # Select elements at (row 1, col 0), (row 5, col 3), (row 7, col 1), and (row 2, col 2)

array([ 4, 23, 29, 10])

In [196]:
# Select rows using a list of indices and then select columns from the resulting array using a list of indices
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # First select rows 1, 5, 7, and 2, then from this new array, select columns 0, 3, 1, and 2

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [197]:
# Select rows using a list of indices and then select columns from the resulting array using a list of indices (same as previous cell)
arr [[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [198]:
# Select rows and columns using lists of indices and assign a value to the selected elements
arr [[1, 5, 7, 2]][:, [0, 3, 1, 2]] = 0 # Select the specified elements and set their values to 0
arr # Display the modified array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [199]:
# Create and reshape an array with a range of numbers
arr = np.arange(15).reshape((3, 5)) # Create an array with numbers from 0 to 14 and reshape it to 3 rows and 5 columns
arr # Display the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [200]:
# Transpose the array
arr.T # Return the transpose of the array (rows become columns, and columns become rows)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [201]:
# Create a new 2D NumPy array
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1],[1, 0, 1]]) # Create a 5x3 array
arr # Display the array

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [202]:
# Perform matrix multiplication using np.dot()
np.dot(arr.T, arr) # Compute the dot product of the transpose of arr and arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [203]:
# Perform matrix multiplication using the @ operator (preferred in newer Python versions)
arr.T @ arr # Compute the matrix multiplication of the transpose of arr and arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [204]:
# Display the array 'arr'
arr # Display the array

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [205]:
# Swap the axes of the array
arr.swapaxes(0, 1) # Swap the first axis (rows) with the second axis (columns)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [206]:
# Generate random samples from a standard normal distribution
samples = np.random.standard_normal(size=(4, 4)) # Generate a 4x4 array of random numbers from the standard normal distribution (mean=0, std dev=1)
samples # Display the array

array([[ 0.3253, -0.545 , -0.2917,  0.4335],
       [ 1.5696,  0.744 ,  0.2316, -0.7761],
       [ 0.9028, -1.0175,  0.5353,  0.9282],
       [ 1.1146, -0.6235, -0.0597, -0.0189]])

In [207]:
from random import normalvariate # Import normalvariate function from the random module
N = 1000000 # Set the number of samples

%timeit samples = [normalvariate(0, 1) for _ in range(N)] # Measure the time to generate N samples using Python's normalvariate
%timeit np.random.standard_normal(N) # Measure the time to generate N samples using NumPy's standard_normal

663 ms ± 35.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
29.6 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [208]:
# Create a new random number generator instance with a seed
rng = np.random.default_rng(seed=12345) # Create a new Generator object with a specified seed for reproducibility
data = rng.standard_normal ((2, 3)) # Generate a 2x3 array of random numbers using the new generator

In [209]:
# Check the type of the random number generator object
type(rng) # Get the type of the 'rng' object

numpy.random._generator.Generator

In [210]:
# Create a 1D array with a range of numbers
arr = np.arange(10) # Create an array with numbers from 0 to 9
arr # Display the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
# Compute the square root of each element in the array
np.sqrt(arr) # Apply the square root function element-wise to the array

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [212]:
# Compute the exponential of each element in the array
np.exp(arr) # Apply the exponential function (e^x) element-wise to the array

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [213]:
# Generate two arrays of random numbers from a standard normal distribution
x = rng.standard_normal(8) # Generate an array of 8 random numbers
y = rng.standard_normal(8) # Generate another array of 8 random numbers
x # Display the array x

array([-1.3678,  0.6489,  0.3611, -1.9529,  2.3474,  0.9685, -0.7594,
        0.9022])

In [214]:
# Display the array y
y # Display the array y

array([-0.467 , -0.0607,  0.7888, -1.2567,  0.5759,  1.399 ,  1.3223,
       -0.2997])

In [215]:
# Compute the element-wise maximum of two arrays
np.maximum(x, y) # Return an array containing the element-wise maximum of x and y

array([-0.467 ,  0.6489,  0.7888, -1.2567,  2.3474,  1.399 ,  1.3223,
        0.9022])

In [216]:
# Generate an array of random numbers and scale them
arr = rng.standard_normal(7) * 5 # Generate an array of 7 random numbers and multiply each by 5
arr # Display the array

array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

In [217]:
# Separate the fractional and integer parts of each element in an array
remainder, whole_part = np.modf(arr) # Return the fractional and integer parts of each element as two separate arrays
remainder # Display the remainder array

array([ 0.5146, -0.1079, -0.7909,  0.2474, -0.718 , -0.4084,  0.6237])

In [218]:
# Display the whole part array
whole_part # Display the whole_part array

array([ 4., -8., -0.,  2., -6., -0.,  8.])

In [219]:
# Display an array and perform element-wise addition into a new array
arr # Display the array 'arr'
out = np.zeros_like(arr) # Create an array of zeros with the same shape and dtype as 'arr'
np.add(arr, 1) # Add 1 to each element of 'arr' (result is not stored)

array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [220]:
# Perform element-wise addition and store the result in a specified output array
np.add(arr, 1, out= out) # Add 1 to each element of 'arr' and store the result in the 'out' array
out # Display the 'out' array

array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [221]:
# Create a grid of points using np.meshgrid
points = np.arange(-5, 5, 0.001) # Create a 1D array of numbers from -5 to 5 with a step of 0.001
xs, ys = np.meshgrid(points, points) # Create 2D coordinate arrays from the 1D array 'points'
ys # Display the 'ys' array

array([[-5.   , -5.   , -5.   , ..., -5.   , -5.   , -5.   ],
       [-4.999, -4.999, -4.999, ..., -4.999, -4.999, -4.999],
       [-4.998, -4.998, -4.998, ..., -4.998, -4.998, -4.998],
       ...,
       [ 4.997,  4.997,  4.997, ...,  4.997,  4.997,  4.997],
       [ 4.998,  4.998,  4.998, ...,  4.998,  4.998,  4.998],
       [ 4.999,  4.999,  4.999, ...,  4.999,  4.999,  4.999]])

In [222]:
# Compute a function of the meshgrid coordinates
z = np.sqrt(xs ** 2 + ys ** 2) # Compute the square root of the sum of squares of corresponding elements in xs and ys
z # Display the resulting array 'z'

array([[7.0711, 7.0704, 7.0697, ..., 7.0689, 7.0697, 7.0704],
       [7.0704, 7.0697, 7.0689, ..., 7.0682, 7.0689, 7.0697],
       [7.0697, 7.0689, 7.0682, ..., 7.0675, 7.0682, 7.0689],
       ...,
       [7.0689, 7.0682, 7.0675, ..., 7.0668, 7.0675, 7.0682],
       [7.0697, 7.0689, 7.0682, ..., 7.0675, 7.0682, 7.0689],
       [7.0704, 7.0697, 7.0689, ..., 7.0682, 7.0689, 7.0697]])